### ISSUE TITLE
Não é possível enviar link de convite

### ISSUE THREAD

**Issue by lucgauer** [lucasinocente/simple-messenger#15]
Aparentemente uma função [`sendAuthLinkToEmail`](https://github.com/lucasinocente/simple-messenger/blob/master/src/containers/Login/Login.js#L23) foi chamada de forma indevida, sem passar o argumento [`event`](https://github.com/lucasinocente/simple-messenger/blob/master/src/containers/Login/Login.js#L53).

Isto acaba quebrando a aplicação :-(

**Comment by lucasinocente** [comment]
Boa maluco!
