### ISSUE TITLE
Deletar texto do campo de mensagem após enviar mensagem

### ISSUE THREAD

**Issue by lucasinocente** [lucasinocente/simple-messenger#20]
Hoje precisamos deletar manualmente o texto do campo após enviar uma mensagem

**Comment by IvanSanchezSalvador** [comment]
Hi, i can help you, can you give me the data base information? It's no necessary the correct db. Thanks.

**Comment by lucasinocente** [comment]
Hi @IvanSanchezSalvador sorry but I dont have a default db information.

You need to install and configure your Firebase project to work. I can explain better in a new docs, what you think?

thanks

**Comment by IvanSanchezSalvador** [comment]
Ok perfect!

**Comment by lucasinocente** [comment]
> Ok perfect!

I will work on this night

**Comment by lucasinocente** [comment]
@IvanSanchezSalvador I will work on this night

**Comment by lucasinocente** [comment]
@IvanSanchezSalvador Hi! Please, take a look if this can help you?

https://github.com/lucasinocente/simple-messenger/blob/master/README.md

**Comment by lucasinocente** [comment]
Feito em https://github.com/lucasinocente/simple-messenger/pull/24
