### ISSUE TITLE
Na tela de login, fazer e-mail ser enviado ao pressionar enter

### ISSUE THREAD

**Issue by lucasinocente** [lucasinocente/simple-messenger#21]
Hoje, somente clicando no botão que a ação é executada

**Comment by gabriel-arauj** [comment]
olá. Gostaria de ajudar.

**Comment by lucasinocente** [comment]
Oi @gabriel-arauj tudo bom? Achei muito boa a tua solução.

O que tu acha de em vez de setar no enter, refatorar pra passar no onSubmit do formulário?
