### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by lucasinocente** [lucasinocente/simple-messenger#25]
Olá! 

- Precisamos avisar pro admin que um novo usuário está enviando mensagens 
- Também precisamos avisar o usuário que recebeu uma nova mensagem do admin
- Esse aviso só deve acontecer se o usuário não estiver com o app aberto

**Comment by smkamranqadri** [comment]
Would like to take this issue, please assign.

Also will be using PWA to generate token and save it. Then a cloud function will run on every message save to send the notification.

**Comment by smkamranqadri** [comment]
Got it, but it was not handled that if user is admin then show messages instead of conversations. 

And obviously admin can't chat with himself so he should be skipped from the list.

**Comment by lucasinocente** [comment]
Hi @smkamranqadri thanks!
So, we can use Create React App's service worker?
We already use create react app.

You can start service worker changing at 'src > index.js' line 12 to 'serviceWorker.register();'

What you think?

**Comment by lucasinocente** [comment]
We need use minimal server to get minimal cost

**Comment by smkamranqadri** [comment]
Well, we can but firebase simple service worker will do the trick.

Also firebase free tier is good for database, hosting and cloud functions.

**Comment by smkamranqadri** [comment]
All work is done but I got stuck with the notification sent to admin as messages don't have the admin id, it's only have the sender so if admin send message then user will receive the notification where when user send message we don't have admin id to get the token and send notification. 

So we need to make some changes, like making admin node like user node.

**Comment by lucasinocente** [comment]
@smkamranqadri hmm okay, I trust you will do the best solution :)

**Comment by smkamranqadri** [comment]
This issue took may whole day!

**Comment by smkamranqadri** [comment]
Anyhow pushing the code and creating pull request so you can checkout the code and may test locally.

**Comment by smkamranqadri** [comment]
forget to update the readme file, will update in the end.

**Comment by smkamranqadri** [comment]
Also some suggestions...

1. For admin, there is no way to know that who is he chatting with.
2. Try/Catch didn't implemented for the sending message.
3. Toaster should also be implemented, I suggest. 
4. UI needs a lot improvement.
5. Internationational needs to be done too, I don't understand the language.
6. There is bug with input field, check console while typing.
7. There was also a bug on the contact list repeating the key attribute issue, I solved it.
8. Title of the page was not set so I updated that too.

**Comment by lucasinocente** [comment]
Dude, you are doing a great job! Thanks for this!

I will create this issues this night and yes, UI is shit for now. I have a friend designer and he will help with UI. 

What you think I create a telegram group to talk about the project?

**Comment by smkamranqadri** [comment]
Thanks for the appreciation, unfortunately telegram doesn't work here so slack or gitter or another platform suits you.

**Comment by smkamranqadri** [comment]
Also one more suggestion, we need to add back button for admin to go back and see the contact list, something like this.

**Comment by smkamranqadri** [comment]
Found a simple solution for the admin id, pushing the code.

**Comment by smkamranqadri** [comment]
Code is push, please check.

**Comment by smkamranqadri** [comment]
Please create more issue, I'll contribute more.

**Comment by lucasinocente** [comment]
Thansk for help dude! I will create more features yes :)

**Comment by smkamranqadri** [comment]
If you think fits, add me as a contributor and assign tasks, I will available for more opensource projects.

**Comment by smkamranqadri** [comment]
smkamranqadri@yahoo.com
