### ISSUE TITLE
Na verificação de usuário se for admin direcionar para a tela de mensagens 

### ISSUE THREAD

**Issue by lucasinocente** [lucasinocente/simple-messenger#27]
Hoje estamos jogando ambos os usuários para a tela de troca de mensagens.

Na tela de verificação precisamos direcionar o admin pra tela de lista de contatos.

**Comment by tclemos** [comment]
Olá Lucas, eu gostaria ajudar com essa issue.
Segui os passos do Readme para configurar o ambiente, já estou com a aplicação rodando e com o Admin configurado, porém, encontrei 2 problemas:

- Não encontrei a tela de contatos
- As mensagens não aparecem na tela quando eu clico em Send

De resto, parece que tudo está funcionando, consegue me ajudar a te ajudar? 

Abraços!

**Comment by tclemos** [comment]
@lucasinocente após pesquisar sobre como identificar se um usuário é admin ou não, de acordo com a documentação do firebase, não seria possível verificar esse tipo de detalhe diretamente no client. 

Esse tipo de lógica precisa ser colocada em um serviço no back-end, onde as credenciais ficam "protegidas" e o sistema pode ter acesso diretamente ao seu firebase para fazer alterações e também consultas.

O script na pasta `admin` já faz algo nesse sentido utilizando o SDK do Firebase para lidar com dados de Admin.

**Comment by lucasinocente** [comment]
Oi @tclemos, obrigado por querer ajudar! 

O componente `src/containers/Messages/Messages.js` é a tela de lista de contatos. Para acessar o endpoint é `/messages`.

Nesse mesmo componente é usado uma função chamada `isAdmin`. Essa função se encontra em `src/firebase/helpers`. Dá uma olhada porque acho que pode te ajudar :)

**Comment by lucasinocente** [comment]
Vê se isso tira as tuas dúvidas por favor e me avisa

**Comment by tclemos** [comment]
Cara, eu não sei nem como te explicar, mas como cheguei na conclusão de que precisaríamos de um back-end para resolver o problema, acabei montando toda uma solução baseada nessa estratégia! Da só uma olhada na branch, pra você ver como eu resolvi o problema dessa forma: https://github.com/tclemos/simple-messenger/tree/backend-server

Nem percebi que o componente `messages` tinha um comportamento diferente, pois a rota `/messages` me enganou e não percebi que ela exibia o componente `messagesList`.

Com essas dicas eu consegui fazer bem rapidinho, sem precisar do back-end, hahaha! 😄 

ta lá o PR #29
