### ISSUE TITLE
Organizar o Código

### ISSUE THREAD

**Issue by eduardocanellas** [lucasinocente/simple-messenger#31]
Ao navegar pelo código, reparei que existem alguns trechos de código repetidos e alguns conceitos diferentes misturados (_Contacts_ dentro de _Messages_). Isso pode dificultar a compreensão de como o projeto pretende evoluir e como manter o código fácil de manter e desenvolver.

Vou propor algumas alterações em um PR: levar _Contacts_ a uma pasta separada, desacoplar o CSS de _Messages_ e _Contacts_, criar um HoC para ser usado como _Layout_ da aplicação e extrair funções repetidas para um lugar só.

**Comment by lucasinocente** [comment]
Obrigado!
