### ISSUE TITLE
Padrão de Código de CSS

### ISSUE THREAD

**Issue by eduardocanellas** [lucasinocente/simple-messenger#33]
Não ficou muito claro para mim se há algum padrão de nomeação de estilos de CSS no projeto. Era bom ter isso claro, pois um bom padrão definido trás muitas vantagens. Eu particularmente sugiro o [CSS BEM](http://getbem.com/introduction/), que é bastante fácil de aprender e começar a usar.

**Comment by lucasinocente** [comment]
Ainda não há padrão de código. Iremos ter uma proposta de layout talvez na próxima semana

**Comment by lucasinocente** [comment]
Oi @eduardocanellas tudo bom? Por favor, me manda o teu e-mail pra eu te adicionar no slack do projeto
