### ISSUE TITLE
Estilizar tela de login

### ISSUE THREAD

**Issue by lucasinocente** [lucasinocente/simple-messenger#5]
Precisamos ter uma tela de login mais bonitinha.

Pode ser seguido esse wireframe:
https://i.imgur.com/sqaBjTu.png

**Comment by agarcia-caicedo** [comment]
Would it be ok if I work on this issue?

**Comment by lucasalacerda** [comment]
@agarcia-caicedo Yeah, sure! Thanks!

**Comment by lucasinocente** [comment]
@agarcia-caicedo did you got how to install the project?

**Comment by lnormanha** [comment]
Tenho interesse em estilizar a tela, mas o @agarcia-caicedo tinha se disponibilizado. Posso fazer mesmo assim?

**Comment by lucasinocente** [comment]
@agarcia-caicedo thanks anyway but @lnormanha finished the new style
